run_config:
  name: cloud-classifier
  author: Suzie Wu
  version: default
  description: Classifies clouds into one of two types.
  dependencies: requirements.txt
  data_source: https://archive.ics.uci.edu/ml/machine-learning-databases/undocumented/taylor/cloud.data
  output: artifacts

create_dataset:
  columns:
    - visible_mean
    - visible_max
    - visible_min
    - visible_mean_distribution
    - visible_contrast
    - visible_entropy
    - visible_second_angular_momentum
    - IR_mean
    - IR_max
    - IR_min
    
generate_features:
  calculate_norm_range:
    IR_norm_range:
      min_col: IR_min
      max_col: IR_max
      mean_col: IR_mean
  log_transform:
    log_entropy: visible_entropy
  multiply:
    entropy_x_contrast:
      col_a: visible_contrast
      col_b: visible_entropy

test_size: 0.4

model_training:
  model_type: "RandomForestClassifier"
  hyperparameters:
    n_estimators: 10
    max_depth: 10

aws:
  upload: True
  bucket_name: qin6843-clouds
  prefix: experiments
